language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -r requirements_dev.txt
  - pip install .
script: py.test tests/

matrix:
  include:
    - python: 3.6
      env: FLAKE8=1
      script: flake8 .
